### ISSUE TITLE
Win7 x64 .exe build request

### ISSUE THREAD

**Issue by brianprichardson** [DanielUranga/trainingdata-tool#3]
It would be very helpful to have an .exe with whatever branch would be most appropriate to create the net training input files from pgn for the material and Elo tiers comparison with the standard CCRL net.  Thank you for your consideration.
Tinker on Leela Discord

**Comment by DanielUranga** [comment]
Just configured Appveyor for automatic builds. Let me know if this works: https://ci.appveyor.com/api/buildjobs/mj34w8qggvwmmu08/artifacts/build%2FRelease%2Ftrainingdata-tool.exe
Will prepare Github releases after this.

**Comment by brianprichardson** [comment]
Crashes after a few seconds
Unhandled exception at 0x000000013FDFCE09 in trainingdata-tool.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

**Comment by brianprichardson** [comment]
Don't know how to re-open the issue, but see my post.
It crashes after a few seconds.

**Comment by DanielUranga** [comment]
I see what happened, lc0 added new magic bitboards code that requires a call to a function to initialize it. This commit https://github.com/DanielUranga/trainingdata-tool/commit/0e9226c35a8cbe067a97838349fba4c77d305f14 will fix the issue. The new binary is: https://ci.appveyor.com/api/buildjobs/7ve53ci9xbq0k83v/artifacts/build%2FRelease%2Ftrainingdata-tool.exe

**Comment by brianprichardson** [comment]
The updated one with the magic fix seems to be working just fine.
