### ISSUE TITLE
Illegal move messages

### ISSUE THREAD

**Issue by brianprichardson** [DanielUranga/trainingdata-tool#4]
Perhaps I am missing something, but why would this game produce illegal move errors?
Note:  This is a v3 .exe, so things may have changed since then.
I'm trying to stay with v3 format as that is what was used with the CCRL "sample" dataset baseline.
Thanks.

[Event "[#13] Hiarcs 12 2CPU - Rybka 3"]
[Site "Local computer"]
[Date "2008.08.12"]
[Round "1"]
[White "Hiarcs 12 MP 2CPU"]
[Black "Rybka 3 x64 2CPU"]
[Result "0-1"]
[WhiteElo "2722"]
[BlackElo "2969"]
[SetUp "1"]
[FEN "1rb1kb1r/pp1ppppp/5n2/5q2/3p4/1NP2P2/PP2P1PP/R2QKBNR w KQk - 0 1"]

1.Qxd4 e6 2.e4 Qf4 3.Qxa7 Qc7 4.Bd3 Be7 5.Ne2 d5 6.Bb5+ Kf8 7.exd5 Nxd5 8.
Qf2 g6 9.O-O Kg7 10.f4 Ra8 11.a3 Rd8 12.Rae1 Kg8 13.Ned4 Bf6 14.Rd1 e5 15.
fxe5 Bxe5 16.Nf3 Bg4 17.Rd3 Bxf3 18.Rxf3 f5 19.Nd4 Qd6 20.Kh1 Qc5 21.a4 
Bxd4 22.cxd4 Qd6 23.b3 Rac8 24.Bc4 Kg7 25.g4 f4 26.Qh4 Rd7 27.Rh3 Kh8 28.
Qh6 b6 29.Rf2 Re7 30.Kg2 Rce8 31.Bb5 Rd8 32.Rhf3 Re4 33.h3 Rf8 34.Kg1 Rxd4
35.Bf1 Rd1 36.h4 Rf6 37.g5 Rf7 38.h5 Rg7 39.hxg6 Rxg6 40.Qh4 h6 41.Rg2 Ne3
42.Qxf4 Qxf4 43.Rxf4 Nxg2 44.Kxg2 Rxg5+ 45.Kh3 Kg7 46.Kh4 Kg6 47.Rf3 Rd4+ 
48.Kh3 Kh5 49.Kh2 Rh4+ 50.Bh3 Re5 51.Kg2 Rhe4 52.Rf6 Re2+ 53.Kf1 Re1+ 54.
Kg2 R5e2+ 55.Rf2 Kg5 56.Rxe2 Rxe2+ 57.Kf3 Rb2 58.Bf1 Rxb3+ 59.Kg2 Re3 60.
Kf2 Re7 61.Bc4 Rc7 62.Bd5 Rc1 63.Be6 h5 64.a5 bxa5 65.Ke3 Re1+ 66.Kd2 Rxe6
67.Kc3 h4 68.Kb3 h3 69.Kc4 h2 70.Kd3 h1=Q 71.Kd4 Qe4+ 72.Kc3 Rc6+ 73.Kb2 
Qb4+ 74.Ka2 Rc2+ 75.Ka1 Qe1# 0-1

This is only one game in a large file (800+K games).
Below is some of the output:

illegal move "Qxd4" at line 8459288, column 2illegal move "e6" at line 8459288, column 7illegal move "Qf4" at line 8459288, column 15illegal move "Qxa7" at line 8459288,
 column 21illegal move "Qc7" at line 8459288, column 26illegal move "Bd3" at line 8459288, column 32illegal move "Be7" a
t line 8459288, column 36illegal move "Ne2" at line 8459288, column 42illegal move "d5" at line 8459288, column 46illega
l move "Bb5+" at line 8459288, column 51illegal move "Kf8" at line 8459288, column 56illegal move "exd5" at line 8459288
, column 62illegal move "Nxd5" at line 8459288, column 67illegal move "Qf2" at line 8459289, column 0illegal move "g6" a
t line 8459289, column 4illegal move "O-O" at line 8459289, column 9illegal move "Kg7" at line 8459289, column 13illegal
 move "Ra8" at line 8459289, column 23illegal move "Rd8" at line 8459289, column 33illegal move "Rae1" at line 8459289,
column 40illegal move "Kg8" at line 8459289, column 45illegal move "Ned4" at line 8459289, column 52illegal move "Bf6" a
t line 8459289, column 57illegal move "Rd1" at line 8459289, column 64illegal move "e5" at line 8459289, column 68illega
l move "fxe5" at line 8459290, column 0illegal move "Bxe5" at line 8459290, column 5illegal move "Bg4" at line 8459290,
column 17illegal move "Rd3" at line 8459290, column 24illegal move "Bxf3" at line 8459290, column 28illegal move "Rxf3"
at line 8459290, column 36illegal move "f5" at line 8459290, column 41illegal move "Nd4" at line 8459290, column 47illeg
al move "Qd6" at line 8459290, column 51illegal move "Kh1" at line 8459290, column 58illegal move "Qc5" at line 8459290,
 column 62illegal move "Bxd4" at line 8459291, column 0illegal move "cxd4" at line 8459291, column 8illegal move "Qd6" a
t line 8459291, column 13illegal move "Rac8" at line 8459291, column 23illegal move "Bc4" at line 8459291, column 31ille
gal move "Kg7" at line 8459291, column 35illegal move "f4" at line 8459291, column 45illegal move "Qh4" at line 8459291,
 column 51illegal move "Rd7" at line 8459291, column 55illegal move "Rh3" at line 8459291, column 62illegal move "Kh8" a
t line 8459291, column 66illegal move "Qh6" at line 8459292, column 0illegal move "b6" at line 8459292, column 4illegal
move "Rf2" at line 8459292, column 10illegal move "Re7" at line 8459292, column 14illegal move "Kg2" at line 8459292, co
lumn 21illegal move "Rce8" at line 8459292, column 25illegal move "Bb5" at line 8459292, column 33illegal move "Rd8" at
line 8459292, column 37illegal move "Rhf3" at line 8459292, column 44illegal move "Re4" at line 8459292, column 49illega
l move "Rf8" at line 8459292, column 59illegal move "Kg1" at line 8459292, column 66illegal move "Rxd4" at line 8459292,
 column 70illegal move "Bf1" at line 8459293, column 3illegal move "Rd1" at line 8459293, column 7illegal move "Rf6" at
line 8459293, column 17illegal move "g5" at line 8459293, column 24illegal move "Rf7" at line 8459293, column 27illegal
move "h5" at line 8459293, column 34illegal move "Rg7" at line 8459293, column 37illegal move "hxg6" at line 8459293, co
lumn 44illegal move "Rxg6" at line 8459293, column 49illegal move "Qh4" at line 8459293, column 57illegal move "h6" at l
ine 8459293, column 61illegal move "Rg2" at line 8459293, column 67illegal move "Ne3" at line 8459293, column 71illegal
move "Qxf4" at line 8459294, column 3illegal move "Qxf4" at line 8459294, column 8illegal move "Rxf4" at line 8459294, c
olumn 16illegal move "Nxg2" at line 8459294, column 21illegal move "Kxg2" at line 8459294, column 29illegal move "Rxg5+"
 at line 8459294, column 34illegal move "Kh3" at line 8459294, column 43illegal move "Kg7" at line 8459294, column 47ill
egal move "Kh4" at line 8459294, column 54illegal move "Kg6" at line 8459294, column 58illegal move "Rf3" at line 845929
4, column 65illegal move "Rd4+" at line 8459294, column 69illegal move "Kh3" at line 8459295, column 3illegal move "Kh5"
 at line 8459295, column 7illegal move "Kh2" at line 8459295, column 14illegal move "Rh4+" at line 8459295, column 18ill
egal move "Bh3" at line 8459295, column 26illegal move "Re5" at line 8459295, column 30illegal move "Kg2" at line 845929
5, column 37illegal move "Rhe4" at line 8459295, column 41illegal move "Rf6" at line 8459295, column 49illegal move "Re2
+" at line 8459295, column 53illegal move "Kf1" at line 8459295, column 61illegal move "Re1+" at line 8459295, column 65
illegal move "Kg2" at line 8459296, column 0illegal move "R5e2+" at line 8459296, column 4illegal move "Rf2" at line 845
9296, column 13illegal move "Kg5" at line 8459296, column 17illegal move "Rxe2" at line 8459296, column 24illegal move "
Rxe2+" at line 8459296, column 29illegal move "Kf3" at line 8459296, column 38illegal move "Rb2" at line 8459296, column
 42illegal move "Bf1" at line 8459296, column 49illegal move "Rxb3+" at line 8459296, column 53illegal move "Kg2" at lin
e 8459296, column 62illegal move "Re3" at line 8459296, column 66illegal move "Kf2" at line 8459297, column 0illegal mov
e "Re7" at line 8459297, column 4illegal move "Bc4" at line 8459297, column 11illegal move "Rc7" at line 8459297, column
 15illegal move "Bd5" at line 8459297, column 22illegal move "Rc1" at line 8459297, column 26illegal move "Be6" at line
8459297, column 33illegal move "h5" at line 8459297, column 37illegal move "a5" at line 8459297, column 43illegal move "
bxa5" at line 8459297, column 46illegal move "Ke3" at line 8459297, column 54illegal move "Re1+" at line 8459297, column
 58illegal move "Kd2" at line 8459297, column 66illegal move "Rxe6" at line 8459297, column 70illegal move "Kc3" at line
 8459298, column 3illegal move "Kb3" at line 8459298, column 13illegal move "Kc4" at line 8459298, column 23illegal move
 "h2" at line 8459298, column 27illegal move "Kd3" at line 8459298, column 33illegal move "h1=Q" at line 8459298, column
 37illegal move "Kd4" at line 8459298, column 45illegal move "Qe4+" at line 8459298, column 49illegal move "Kc3" at line
 8459298, column 57illegal move "Rc6+" at line 8459298, column 61illegal move "Kb2" at line 8459298, column 69illegal mo
ve "Qb4+" at line 8459299, column 0illegal move "Ka2" at line 8459299, column 8illegal move "Rc2+" at line 8459299, colu
mn 12illegal move "Ka1" at line 8459299, column 20illegal move "Qe1#" at line 8459299, column 24

**Comment by DanielUranga** [comment]
The illegal moves issue you are seeing looks related to the FEN support that was missing until a few days ago. Could you try this exe: https://ci.appveyor.com/api/buildjobs/6pvsiylnhnffk8un/artifacts/build%2FRelease%2Ftrainingdata-tool.exe ? It's from latest master.
The data format will be v4, which includes a superset of all the data included in v3, so it's the one that should be used.

**Comment by brianprichardson** [comment]
Somehow missed the exe fix from 7 days ago.  Will try. Thanks.

**Comment by brianprichardson** [comment]
This version ran without objecting about illegal moves, but I'm not sure the pgn I tried it with had any.  More problematic is that when trying to train a net with the converted output all of my CPU cores pegged at 100% busy  and the net did nothing.  I let it run for more than an hour.  To be fair, the training code I'm using dates back to the sample CCRL dataset, which is from Oct'18 I think.  I suspect it is a version issue.
