### ISSUE TITLE
Won’t build on Linux

### ISSUE THREAD

**Issue by dkappe** [DanielUranga/trainingdata-tool#5]
It seems some windows specific dependencies have slipped in:

```
/home/dkappe/data/src/trainingdata-tool/polyglot/src/getopt.h:64:10: fatal error: crtdefs.h: No such file or directory
 #include <crtdefs.h>
          ^~~~~~~~~~~
compilation terminated.
```

**Comment by DanielUranga** [comment]
I develop the tool on Linux, so this is kind of weird. Probably will have to setup Linux CI to catch this stuff.
Not sure if I will able to fix this before weekend, but will try.

**Comment by DanielUranga** [comment]
Had integrated CircleCI and it's building ok: https://circleci.com/gh/DanielUranga/trainingdata-tool/6
Which Linux distribution are you using?
